# VIBE — Genesis collection · single source of truth for all 30 NFTs.
# `python3 collection/generate.py` builds: metadata/*.json, collection/collection.json,
# prompts/*.md, docs/CATALOG.md, docs/ATTRIBUTES.md.
#
# status: "rendered" → real 3D render exists in assets/<slug>/ (engine/objects/<slug>.js)
#         "concept"  → spec + production prompt only; render pending

NFTS = []


def nft(**k):
    k.setdefault("status", "concept")
    NFTS.append(k)


# ───────────────────────────────────────── 01–10 (brief) ─────────────────────────────────────────
nft(n=1, slug="01-vibe-heart", name="Vibe Heart", ru="Сердце Vibe", rarity="Uncommon", price=10, status="rendered",
    category="Jewelry", obj="Pendant", material="Pink Crystal", metal="Rose Gold", color="Dusty Pink",
    emotion="Tenderness", connection="Same Wavelength", effect="Heartbeat Glow",
    concept="«Мы на одной волне.» Фирменный кулон коллекции: то, что носят у сердца. Внутри — свой маленький свет и своя орбита: у каждого из двоих есть собственный мир, и они совпали.",
    design="Пухлое прозрачное сердце из розово-лавандового стекла в тонком rose-gold ободке. Внутри парит огранённый светящийся кристалл, вокруг него — волосяная орбита с жемчужной бусиной. В толще стекла — звёздная пыль. Сверху: петля-бейл, соединительное кольцо и болт-замок.",
    silhouette="Сердце + вертикальная фурнитура сверху (бейл → кольцо → замок). Читается как «кулон».",
    materials=["pink-lavender glass (transmission, IOR 1.48)", "polished rose gold with micro-scratches", "emissive faceted crystal", "pearl bead", "metallic stardust"],
    colors=["Dusty Pink", "Soft Lavender", "Rose Gold", "Pearl White"],
    meaning="Совпадение вайба — главное, что делает знакомство настоящим.",
    anim="3 с · кулон поворачивается на кольце (±29°) и чуть качается маятником; два удара сердца → вспышка кристалла; мини-орбита делает оборот, бусина — два в обратную сторону; пыль мерцает.",
    desc="A designer crystal pendant with its own light inside — for two people on the same wavelength.",
    season="Valentine — Ruby Vibe (рубиновое стекло, красное золото) · Winter — Frost Vibe (ледяное стекло, белое золото)",
    prompt="a luxury designer pendant: a puffy transparent pink-lavender glass heart set in a thin polished rose-gold bezel, a small faceted glowing pink crystal floating inside the glass with a hair-thin rose-gold orbit ring and a tiny pearl bead around it, fine sparkling stardust suspended in the glass, a rose-gold bail, jump ring and bolt-ring clasp at the top")

nft(n=2, slug="02-key-to-you", name="Key to You", ru="Ключ к тебе", rarity="Uncommon", price=10, status="rendered",
    category="Secret Symbols", obj="Key", material="Pink Crystal", metal="Rose Gold", color="Rose Gold",
    emotion="Trust", connection="Trust", effect="Inner Glow",
    concept="«Ты открыл(а) мне что-то настоящее.» Доверие как единственный ключ, который подходит к человеку.",
    design="Ключ из полированного rose gold. Головка — хрустальное розовое сердце в металлической рамке со светящимся сердцем внутри и звёздной пылью. На стыке — воротник из двух колец и лавандовая хрустальная втулка. В бородке прорезано сердце — оно и есть механизм.",
    silhouette="Длинный диагональный ключ с сердцем-головкой и прямоугольной бородкой. Узнаётся за 1 секунду.",
    materials=["polished rose gold with micro-scratches", "pink crystal (transmission)", "lavender crystal barrel", "emissive inner heart", "metallic stardust"],
    colors=["Rose Gold", "Dusty Pink", "Lilac", "Pearl White"],
    meaning="Настоящее открывается не взломом, а доверием.",
    anim="3 с · ключ медленно поворачивается вокруг своей оси (±49°), как в замке; когда сердце смотрит на зрителя, оно загорается; лёгкий float.",
    desc="A rose-gold key with a crystal heart — for the person who unlocked something real.",
    season="Valentine — Ruby Key · Spring — Mint Key (мятное стекло, champagne gold) · Anniversary — Engraved Key (дата на бородке)",
    prompt="a luxury rose-gold key: the bow is a puffy pink crystal heart inside a polished rose-gold frame with a small softly glowing heart and sparkling dust inside, a collar of two rose-gold rings with a short lavender crystal barrel, a slim polished rose-gold shaft, and a rectangular bit with a heart-shaped cut-out, displayed diagonally")

nft(n=3, slug="03-love-lock", name="Love Lock", ru="Замок любви", rarity="Uncommon", price=9,
    category="Connection", obj="Padlock", material="Pink Crystal", metal="Rose Gold", color="Dusty Pink",
    emotion="Safety", connection="Commitment", effect="Opening",
    concept="Замок, который хочется закрыть вдвоём: обещание без давления.",
    design="Миниатюрный навесной замок: корпус из толстого розового хрусталя со скруглёнными гранями, дужка из полированного rose gold. Внутри корпуса парит маленькое сердце из жемчужной эмали. Скважина обрамлена тонким золотым кантом.",
    silhouette="Классический силуэт навесного замка с полукруглой дужкой.",
    materials=["thick pink crystal", "polished rose gold", "pearl enamel heart"],
    colors=["Dusty Pink", "Rose Gold", "Pearl White"],
    meaning="Безопасность — основа настоящей связи.",
    anim="3 с · дужка поднимается на 8° и мягко защёлкивается; сердце внутри качается, как в жидкости; блик скользит по хрусталю.",
    desc="A pink crystal padlock with a floating heart — a promise you close together.",
    season="Winter — Ice Lock · Valentine — Ruby Lock",
    prompt="a miniature luxury padlock: a thick rounded pink crystal body with a small pearl-enamel heart floating inside, a polished rose-gold shackle, a fine rose-gold rim around the keyhole")

nft(n=4, slug="04-secret-message", name="Secret Message", ru="Тайное послание", rarity="Common", price=4,
    category="Love Letters", obj="Envelope", material="Pearl Paper", metal="Rose Gold", color="Pearl White",
    emotion="Anticipation", connection="First Words", effect="Opening",
    concept="Сообщение, которое не отправили бы в общий чат.",
    design="Маленький конверт из перламутровой бумаги с rose-gold кантом по краям клапана. Печать — хрустальное сердце огранки «кабошон».",
    silhouette="Горизонтальный конверт с треугольным клапаном и круглой печатью по центру.",
    materials=["pearlescent paper", "rose-gold foil edges", "pink crystal cabochon seal"],
    colors=["Pearl White", "Rose Gold", "Dusty Pink"],
    meaning="Самые важные слова — личные.",
    anim="3 с · клапан приоткрывается, изнутри поднимается мягкий свет, печать вспыхивает; клапан закрывается.",
    desc="A pearl envelope sealed with a crystal heart. Some words are only for one person.",
    season="Valentine — Blush Letter · New Year — Midnight Letter (чёрная бумага, champagne gold)",
    prompt="a small luxury envelope made of pearlescent paper with thin rose-gold foil edges along the flap, sealed with a pink crystal heart cabochon, soft light escaping from inside")

nft(n=5, slug="05-match", name="Match", ru="Совпали", rarity="Rare", price=25,
    category="Dating", obj="Twin Crystals", material="Iridescent Crystal", metal="Champagne Gold", color="Soft Lavender",
    emotion="Recognition", connection="Mutual", effect="Light Bridge",
    concept="«Совпали.» Два разных кристалла медленно находят друг друга — и между ними появляется свет.",
    design="Два вертикальных кристалла разной огранки (один лавандовый, другой розовый) на тонких champagne-gold основаниях. Их грани зеркальны: вместе они образуют сердце.",
    silhouette="Две вертикальные капли-кристаллы, которые в контакте складываются в сердце.",
    materials=["iridescent crystal", "pink crystal", "champagne gold bases", "volumetric light"],
    colors=["Soft Lavender", "Dusty Pink", "Champagne", "Pearl White"],
    meaning="Взаимность — это когда двое делают шаг навстречу.",
    anim="4 с · кристаллы сближаются, касаются, между ними вспыхивает тонкая световая нить и складывается сердце; расходятся.",
    desc="Two crystals that fit only each other. When they touch, the light appears.",
    season="Valentine — Ruby Match · Summer — Sunset Match",
    prompt="two tall faceted crystals, one lavender and one pink, standing on slim champagne-gold bases, their inner faces mirror each other so that together they form a heart, a thin thread of soft light between them")

nft(n=6, slug="06-vibe-ring", name="Vibe Ring", ru="Кольцо Vibe", rarity="Uncommon", price=9,
    category="Jewelry", obj="Ring", material="Pink Crystal", metal="Rose Gold", color="Rose Gold",
    emotion="Devotion", connection="Promise", effect="Levitation",
    concept="Минималистичное кольцо-обещание: не помолвка, а «я серьёзно».",
    design="Тонкая шинка из rose gold с двумя лапками-коронами; над ними, не касаясь, левитирует огранённое хрустальное сердце.",
    silhouette="Круг кольца + сердце, парящее над ним.",
    materials=["polished rose gold", "pink crystal heart (heart cut)"],
    colors=["Rose Gold", "Dusty Pink", "Pearl White"],
    meaning="Обещание может быть лёгким — и всё равно настоящим.",
    anim="3 с · кольцо медленно вращается, сердце парит и поворачивается в противофазе, по шинке бежит блик.",
    desc="A rose-gold ring with a crystal heart floating above it — a light promise that still means it.",
    season="Valentine — Ruby Ring · Anniversary — Engraved Ring",
    prompt="a minimalist polished rose-gold ring with a thin band and two tiny prongs, a heart-cut pink crystal levitating just above the prongs without touching")

nft(n=7, slug="07-butterfly-effect", name="Butterfly Effect", ru="Эффект бабочки", rarity="Rare", price=25,
    category="Attraction", obj="Butterfly", material="Iridescent Crystal", metal="Rose Gold", color="Soft Mint",
    emotion="Excitement", connection="First Spark", effect="Particles",
    concept="Одно знакомство может изменить всё.",
    design="Хрустальная бабочка: крылья из тонкого полупрозрачного стекла с переливом lavender → pink → mint, тончайшие rose-gold прожилки, тело — нитка жемчуга.",
    silhouette="Симметричная бабочка с раскрытыми крыльями.",
    materials=["thin-film iridescent glass", "rose-gold veins", "pearl body"],
    colors=["Soft Lavender", "Dusty Pink", "Soft Mint", "Rose Gold"],
    meaning="Маленькое «привет» запускает большие изменения.",
    anim="3 с · мягкий взмах крыльев, за ними — шлейф из очень мелких светящихся частиц; перелив по крыльям.",
    desc="A crystal butterfly. One small hello can change everything.",
    season="Spring — Sakura Wings · Winter — Frost Wings",
    prompt="a luxury crystal butterfly with thin translucent glass wings shifting from lavender to pink to mint, delicate polished rose-gold veins, a body made of tiny pearls")

nft(n=8, slug="08-first-date", name="First Date", ru="Первое свидание", rarity="Uncommon", price=8,
    category="First Meeting", obj="Café Table", material="Glossy Ceramic", metal="Champagne Gold", color="Pearl White",
    emotion="Nervous Joy", connection="First Meeting", effect="Steam Heart",
    concept="Тот самый столик, где всё началось.",
    design="Миниатюрный круглый столик из розового мрамора на одной champagne-gold ножке. Две фарфоровые чашки с жемчужной глазурью; между ними — крошечное хрустальное сердце. Пар из чашек переплетается в сердце.",
    silhouette="Круглый столик на ножке с двумя чашками.",
    materials=["pink marble", "glossy pearl porcelain", "champagne gold", "crystal heart"],
    colors=["Pearl White", "Dusty Pink", "Champagne"],
    meaning="Первое свидание — маленькая сцена большой истории.",
    anim="3 с · два тонких потока пара поднимаются и сплетаются в сердце, растворяются; сердце на столе мерцает.",
    desc="A tiny café table for two. The steam already knows.",
    season="Autumn — Pumpkin Café · Winter — Cocoa Night",
    prompt="a miniature round café table with a pink marble top on a single champagne-gold leg, two small glossy pearl porcelain cups, a tiny crystal heart between them, two wisps of steam intertwining into a heart")

nft(n=9, slug="09-love-note", name="Love Note", ru="Записка", rarity="Common", price=3,
    category="Messages", obj="Folded Note", material="Pearl Paper", metal="None", color="Soft Lavender",
    emotion="Sweetness", connection="First Words", effect="Unfolding",
    concept="Записка, которую передают через стол.",
    design="Сложенная вдвое карточка из плотной лавандовой бумаги с рваным краем; на лицевой стороне — тиснёный минимальный символ сердца.",
    silhouette="Карточка домиком (сложенная пополам).",
    materials=["heavy lavender paper with deckle edge", "blind-embossed heart"],
    colors=["Soft Lavender", "Pearl White"],
    meaning="Несколько слов от руки весят больше сотни сообщений.",
    anim="3 с · карточка раскрывается, изнутри — мягкий свет; закрывается.",
    desc="A folded note with one embossed heart. Open it slowly.",
    season="Valentine — Blush Note · Spring — Mint Note",
    prompt="a small folded note card of heavy lavender paper with a soft deckle edge, a minimal blind-embossed heart on the front, warm light glowing from inside the fold")

nft(n=10, slug="10-orbit-heart", name="Orbit Heart", ru="Орбитальное сердце", rarity="Legendary", price=250, status="rendered",
    category="Connection", obj="Orbit Heart", material="Iridescent Crystal", metal="Rose Gold", color="Soft Lavender",
    emotion="Gravity", connection="Same Wavelength", effect="Orbit",
    concept="Главный символ Vibe. Симпатия как гравитация: двое не сталкиваются — они на одной орбите. Сердце пронзено орбитой, внутри — кристалл, вокруг — спутники.",
    design="Крупное прозрачное сердце из толстого iridescent-стекла. Сквозь него проходит полированное rose-gold кольцо с champagne-хайрлайном (часть орбиты видна сквозь стекло, преломлённая). Внутри парит большой огранённый кристалл, в толще — звёздная пыль. По орбите движутся жемчужины и мини-кристаллы.",
    silhouette="Сердце, пронзённое наклонной эллиптической орбитой. Самый узнаваемый силуэт коллекции.",
    materials=["thick iridescent glass (thin-film, dispersion)", "polished rose gold", "champagne gold hairline", "emissive faceted crystal", "pearls", "stardust"],
    colors=["Soft Lavender", "Dusty Pink", "Rose Gold", "Pearl White", "Deep Plum"],
    meaning="Настоящая связь — это гравитация, а не случайность.",
    anim="5 с · три удара сердца; стекло поворачивается ±24° вместе с орбитой; кристалл делает полный оборот; спутники проходят 1–2 круга; пыль мерцает; искры вспыхивают на гранях.",
    desc="The hero of the Vibe collection: an iridescent glass heart pierced by a rose-gold orbit. Real connections only.",
    season="Valentine — Ruby Orbit (1/1) · New Year — Midnight Orbit (дымчатое стекло, champagne gold) · Anniversary — Second Orbit",
    prompt="a large thick transparent iridescent glass heart pierced by a tilted polished rose-gold orbit ring with a thin champagne-gold hairline ring, the part of the ring inside the glass visibly refracted, a large faceted softly glowing pink crystal floating inside the heart, fine sparkling stardust suspended in the glass, small pearls and tiny crystals travelling along the orbit")

# ───────────────────────────────────────── 11–30 (new) ─────────────────────────────────────────
nft(n=11, slug="11-lucky-charm", name="Lucky Charm", ru="Талисман удачи", rarity="Common", price=4,
    category="Luck", obj="Clover Charm", material="Glossy Enamel", metal="Rose Gold", color="Soft Mint",
    emotion="Hope", connection="First Spark", effect="Spin",
    concept="Четырёхлистник, у которого каждый лист — маленькое сердце: удача в знакомствах.",
    design="Подвеска-клевер из четырёх сердечек мятной глянцевой эмали в rose-gold оправе, в центре — жемчужина.",
    silhouette="Крестообразный четырёхлистник.",
    materials=["glossy mint enamel", "rose gold setting", "pearl"], colors=["Soft Mint", "Rose Gold", "Pearl White"],
    meaning="Немного удачи — и встреча случится.",
    anim="3 с · подвеска медленно крутится вокруг вертикали, жемчужина бликует.",
    desc="A four-leaf clover made of four tiny hearts. Luck, but make it romantic.",
    season="St. Patrick — Emerald Clover · Spring — Blossom Clover",
    prompt="a small luxury charm shaped like a four-leaf clover where each leaf is a tiny heart in glossy mint enamel set in polished rose gold, a single pearl in the centre")

nft(n=12, slug="12-night-line", name="Night Line", ru="Ночной звонок", rarity="Common", price=4,
    category="Night Conversations", obj="Phone Handset", material="Lavender Glass", metal="Rose Gold", color="Soft Lavender",
    emotion="Intimacy", connection="Night Talks", effect="Pulse",
    concept="Разговоры до трёх ночи, после которых всё становится ясно.",
    design="Ретро-трубка из лавандового стекла с rose-gold деталями, спиральный провод свит в сердце.",
    silhouette="Изогнутая трубка + спиральный провод-сердце.",
    materials=["lavender glass", "rose gold", "coiled glass cord"], colors=["Soft Lavender", "Rose Gold", "Deep Plum"],
    meaning="Лучшие разговоры случаются ночью.",
    anim="3 с · по проводу бегут световые импульсы, трубка чуть покачивается.",
    desc="A glass handset with a cord coiled into a heart. For the talks that last until 3 a.m.",
    season="Halloween — Midnight Line · Winter — Frost Line",
    prompt="a retro telephone handset made of lavender glass with polished rose-gold details, its coiled cord twisted into the shape of a heart")

nft(n=13, slug="13-chemistry", name="Chemistry", ru="Химия", rarity="Rare", price=22,
    category="Chemistry", obj="Flask", material="Liquid Glass", metal="Champagne Gold", color="Dusty Pink",
    emotion="Attraction", connection="Chemistry", effect="Liquid Merge",
    concept="Между вами есть химия — буквально.",
    design="Тонкостенная колба с двумя жидкостями (розовой и лавандовой), которые смешиваются в пузырь-сердце. Пробка — огранённый кристалл в champagne-gold.",
    silhouette="Колба с узким горлом и круглым дном.",
    materials=["thin borosilicate glass", "two coloured liquids", "crystal stopper", "champagne gold collar"],
    colors=["Dusty Pink", "Soft Lavender", "Champagne"],
    meaning="Некоторые реакции невозможно объяснить — только почувствовать.",
    anim="3 с · жидкости закручиваются и смешиваются, поднимается пузырь в форме сердца; цвет переливается.",
    desc="A glass flask where two colours meet and become one bubble. Chemistry, obviously.",
    season="Valentine — Love Formula · Summer — Sunset Reaction",
    prompt="a delicate laboratory flask of thin clear glass with a pink and a lavender liquid swirling into each other and forming a heart-shaped bubble, a faceted crystal stopper with a champagne-gold collar")

nft(n=14, slug="14-glass-peony", name="Glass Peony", ru="Стеклянный пион", rarity="Uncommon", price=10,
    category="Flowers", obj="Flower", material="Pink Crystal", metal="Champagne Gold", color="Dusty Pink",
    emotion="Admiration", connection="Courtship", effect="Blooming",
    concept="Цветы, которые не завянут.",
    design="Пышный пион из десятков тонких лепестков розового стекла, в центре — жемчужная тычинка; короткий champagne-gold стебель с одним листом.",
    silhouette="Круглая пышная чаша цветка на коротком стебле.",
    materials=["thin pink glass petals", "pearl stamen", "champagne gold stem"], colors=["Dusty Pink", "Pearl White", "Champagne"],
    meaning="Красивый жест, который останется.",
    anim="3 с · лепестки медленно раскрываются и закрываются, внутри вспыхивает жемчуг.",
    desc="A peony of glass petals that never fades.",
    season="Spring — Sakura Peony · Winter — Frost Peony",
    prompt="a lush peony made of dozens of thin translucent pink glass petals with a pearl stamen in the centre, a short champagne-gold stem with one glass leaf")

nft(n=15, slug="15-mixtape", name="Mixtape", ru="Микстейп", rarity="Common", price=4,
    category="Music", obj="Cassette", material="Translucent Acrylic", metal="Rose Gold", color="Soft Lavender",
    emotion="Nostalgia", connection="Shared Taste", effect="Spin",
    concept="Плейлист, собранный для одного человека.",
    design="Кассета из полупрозрачного лавандового акрила, катушки rose gold, одна из них в форме сердца; плёнка с перламутровым переливом.",
    silhouette="Прямоугольная кассета с двумя окнами-катушками.",
    materials=["translucent lavender acrylic", "rose-gold reels", "pearlescent tape"], colors=["Soft Lavender", "Rose Gold", "Pearl White"],
    meaning="Музыка — самый честный способ сказать «ты мне нравишься».",
    anim="3 с · катушки вращаются, по плёнке бежит перламутровый блик.",
    desc="A translucent cassette with a heart-shaped reel. Made for one person only.",
    season="Summer — Festival Tape · Winter — Frost Tape",
    prompt="a cassette tape made of translucent lavender acrylic with polished rose-gold reels, one reel shaped like a heart, pearlescent shimmering tape")

nft(n=16, slug="16-pour-over", name="Pour Over", ru="Пуровер", rarity="Common", price=3,
    category="Coffee", obj="Coffee Dripper", material="Glossy Ceramic", metal="Champagne Gold", color="Pearl White",
    emotion="Comfort", connection="Slow Dating", effect="Liquid Drop",
    concept="Медленный кофе для медленного знакомства.",
    design="Конусная воронка из жемчужной керамики на champagne-gold стойке, под ней — стеклянная чашка; падает одна капля в форме сердца.",
    silhouette="Конус над чашкой — вертикальная двухъярусная форма.",
    materials=["glossy pearl ceramic", "champagne gold stand", "clear glass cup", "coffee"], colors=["Pearl White", "Champagne", "Almost Black"],
    meaning="Лучшее не торопят.",
    anim="3 с · капля-сердце формируется, падает и расходится кругами в чашке.",
    desc="A pearl ceramic dripper and one heart-shaped drop. Good things take time.",
    season="Autumn — Spiced Pour · Winter — Cocoa Pour",
    prompt="a pour-over coffee dripper of glossy pearl ceramic on a slim champagne-gold stand above a small clear glass cup, a single heart-shaped coffee drop falling")

nft(n=17, slug="17-shooting-star", name="Shooting Star", ru="Падающая звезда", rarity="Common", price=4,
    category="Stars", obj="Shooting Star", material="Iridescent Crystal", metal="Champagne Gold", color="Champagne",
    emotion="Wonder", connection="Wish", effect="Trail",
    concept="Загадай желание — пока мы вместе.",
    design="Пятилучевая звезда из iridescent-хрусталя со шлейфом из champagne-gold нитей и мелких кристаллов.",
    silhouette="Звезда с диагональным хвостом.",
    materials=["iridescent crystal", "champagne gold strands", "crystal particles"], colors=["Champagne", "Soft Lavender", "Pearl White"],
    meaning="Ты — сбывшееся желание.",
    anim="3 с · звезда плывёт по дуге, хвост переливается, частицы осыпаются и исчезают (бесшовно).",
    desc="A crystal star with a golden trail. Make a wish.",
    season="New Year — Midnight Star · Summer — Perseids",
    prompt="a five-pointed iridescent crystal star with a long diagonal trail of fine champagne-gold strands and tiny crystals")

nft(n=18, slug="18-moon-locket", name="Moon Locket", ru="Лунный медальон", rarity="Rare", price=20,
    category="Moon", obj="Locket", material="Pearlescent", metal="Champagne Gold", color="Pearl White",
    emotion="Longing", connection="Night Talks", effect="Opening",
    concept="Медальон-полумесяц, внутри которого две звезды.",
    design="Полумесяц из перламутра в champagne-gold оправе, раскрывается на петле; внутри — синее ночное стекло с двумя кристаллами-звёздами.",
    silhouette="Полумесяц на цепочке.",
    materials=["mother-of-pearl", "champagne gold", "deep blue night glass", "crystal stars"], colors=["Pearl White", "Champagne", "Icy Blue", "Deep Plum"],
    meaning="Даже на расстоянии мы под одной луной.",
    anim="4 с · медальон приоткрывается, звёзды внутри вспыхивают по очереди, закрывается.",
    desc="A pearl crescent locket hiding two stars. Same moon, same night.",
    season="Winter — Snow Moon · Halloween — Blood Moon (ruby glass)",
    prompt="a crescent-moon locket of mother-of-pearl in a champagne-gold frame, slightly open on its hinge, revealing deep blue night glass with two small crystal stars inside")

nft(n=19, slug="19-developing-feelings", name="Developing Feelings", ru="Проявляются чувства", rarity="Common", price=4,
    category="Photography", obj="Instant Photo", material="Pearl Paper", metal="Rose Gold", color="Dusty Pink",
    emotion="Nostalgia", connection="Memories", effect="Developing",
    concept="Чувства проявляются, как моментальное фото.",
    design="Карточка моментального фото в перламутровой рамке с rose-gold скрепкой-сердцем; в окне — проявляющийся градиент розового с силуэтом двух сердец (без лиц).",
    silhouette="Квадратная карточка с широким нижним полем, наклон 6°.",
    materials=["pearlescent photo frame", "holographic film", "rose-gold clip"], colors=["Dusty Pink", "Pearl White", "Rose Gold"],
    meaning="Лучшие моменты проявляются не сразу.",
    anim="3 с · изображение проявляется из белого, два сердца сближаются; затем снова светлеет.",
    desc="An instant photo where two hearts slowly develop. Some feelings need a moment.",
    season="Summer — Beach Roll · Autumn — Amber Film",
    prompt="an instant photo print in a pearlescent frame held by a small rose-gold heart-shaped clip, in the image window a soft pink gradient slowly developing with the silhouettes of two hearts, tilted slightly")

nft(n=20, slug="20-take-me-with-you", name="Take Me With You", ru="Возьми меня с собой", rarity="Common", price=4,
    category="Travel", obj="Luggage Tag", material="Glossy Enamel", metal="Rose Gold", color="Lilac",
    emotion="Adventure", connection="Plans Together", effect="Swing",
    concept="Первое совместное путешествие начинается с бирки.",
    design="Багажная бирка из лиловой глянцевой эмали в rose-gold рамке, с сердцем-перфорацией и атласной лиловой лентой.",
    silhouette="Прямоугольная бирка со срезанными углами и петлёй ленты.",
    materials=["glossy lilac enamel", "rose gold frame", "lilac satin ribbon"], colors=["Lilac", "Rose Gold", "Pearl White"],
    meaning="С тобой — куда угодно.",
    anim="3 с · бирка покачивается на ленте, лента колышется.",
    desc="An enamel luggage tag on a satin ribbon. Anywhere, as long as it's together.",
    season="Summer — Riviera Tag · Winter — Alpine Tag",
    prompt="a luxury luggage tag in glossy lilac enamel with a polished rose-gold frame and a heart-shaped punch hole, tied with a lilac satin ribbon")

nft(n=21, slug="21-true-north", name="True North", ru="Мой север", rarity="Epic", price=60,
    category="Travel", obj="Compass", material="Optical Crystal", metal="Champagne Gold", color="Champagne",
    emotion="Certainty", connection="Direction", effect="Needle Seek",
    concept="Стрелка, которая всегда находит тебя.",
    design="Карманный компас: champagne-gold корпус, крышка из оптического хрусталя, циферблат почти чёрный с перламутровыми созвездиями, стрелка заканчивается сердцем.",
    silhouette="Круг с ушком наверху — компас.",
    materials=["champagne gold", "optical crystal cover", "almost-black dial", "mother-of-pearl constellations"],
    colors=["Champagne", "Almost Black", "Pearl White", "Dusty Pink"],
    meaning="Когда находишь своего человека — направление понятно.",
    anim="4 с · стрелка колеблется и находит север (затухающая пружина), сердце загорается, созвездия мерцают.",
    desc="A crystal compass whose needle ends in a heart. It always points to you.",
    season="Winter — Polar North · Valentine — Ruby North",
    prompt="a luxury pocket compass with a champagne-gold case and a domed optical crystal cover, an almost-black dial with mother-of-pearl constellations, a slim golden needle ending in a tiny heart")

nft(n=22, slug="22-attraction", name="Attraction", ru="Притяжение", rarity="Rare", price=22,
    category="Attraction", obj="Perfume Bottle", material="Pink Crystal", metal="Rose Gold", color="Dusty Pink",
    emotion="Desire", connection="Attraction", effect="Liquid Shimmer",
    concept="Аромат, который остаётся в памяти.",
    design="Толстостенный флакон из розового хрусталя с внутренним «сердцем»-полостью; крышка — rose-gold сфера; жидкость с шиммером.",
    silhouette="Прямоугольный флакон со сферической крышкой.",
    materials=["thick pink crystal", "shimmering liquid", "rose gold cap"], colors=["Dusty Pink", "Rose Gold", "Lilac"],
    meaning="Притяжение невозможно объяснить — только узнать.",
    anim="3 с · шиммер медленно кружится внутри, флакон дышит, блик скользит.",
    desc="A pink crystal flacon with a heart-shaped core. The kind of scent you remember.",
    season="Autumn — Amber Attraction · Winter — Cashmere Attraction",
    prompt="a thick-walled pink crystal perfume bottle with a heart-shaped hollow inside the glass, shimmering liquid, a polished rose-gold sphere cap")

nft(n=23, slug="23-our-little-world", name="Our Little World", ru="Наш маленький мир", rarity="Epic", price=55,
    category="Memories", obj="Snow Globe", material="Optical Crystal", metal="Rose Gold", color="Icy Blue",
    emotion="Belonging", connection="Memories", effect="Snowfall",
    concept="Маленький мир, где есть только вы.",
    design="Хрустальный шар на rose-gold основании; внутри — миниатюрная скамейка, фонарь и два огонька; падает розовый «снег».",
    silhouette="Сфера на низком основании.",
    materials=["optical crystal sphere", "rose gold base", "miniature bench and lamp", "pink snow particles"],
    colors=["Icy Blue", "Rose Gold", "Dusty Pink", "Pearl White"],
    meaning="Общие воспоминания — это и есть ваш мир.",
    anim="5 с · снег медленно падает по кругу (бесшовно), огоньки дышат, фонарь мерцает.",
    desc="A crystal globe with a bench, a lamp and two lights. A world just big enough for two.",
    season="Winter — Snow Night · Spring — Petal Fall",
    prompt="an optical crystal snow globe on a polished rose-gold base, inside a miniature bench and a tiny street lamp with two soft glowing lights, slow falling pink snow")

nft(n=24, slug="24-fortune-cookie", name="Fortune Cookie", ru="Печенье с предсказанием", rarity="Common", price=3,
    category="Luck", obj="Fortune Cookie", material="Glossy Ceramic", metal="Champagne Gold", color="Champagne",
    emotion="Playfulness", connection="First Spark", effect="Reveal",
    concept="Предсказание, которое сбылось.",
    design="Печенье с предсказанием из глянцевой керамики цвета шампанского с золотой глазурью по краю; из щели выглядывает перламутровая лента.",
    silhouette="Узнаваемая форма fortune cookie.",
    materials=["glossy champagne ceramic", "gold lustre glaze", "pearl paper slip"], colors=["Champagne", "Pearl White"],
    meaning="Иногда судьба пишет коротко.",
    anim="3 с · бумажка выезжает и мягко светится, затем прячется.",
    desc="A porcelain fortune cookie. Your fortune: them.",
    season="Lunar New Year — Red Fortune · Valentine — Blush Fortune",
    prompt="a fortune cookie made of glossy champagne-coloured porcelain with gold lustre on the edge, a pearl paper slip peeking out of the fold")

nft(n=25, slug="25-astrolabe", name="Astrolabe of Us", ru="Астролябия", rarity="Epic", price=65,
    category="Stars", obj="Astrolabe", material="Iridescent Crystal", metal="Rose Gold", color="Deep Plum",
    emotion="Destiny", connection="Destiny", effect="Rings Rotation",
    concept="Прибор, который вычисляет, когда звёзды сойдутся.",
    design="Сфера из трёх rose-gold колец (армиллярная), в центре — кристалл-сердце; на кольцах гравированы созвездия, жемчужины-планеты.",
    silhouette="Ажурная армиллярная сфера на ножке.",
    materials=["polished rose gold rings", "iridescent crystal heart", "pearl planets"], colors=["Rose Gold", "Deep Plum", "Soft Lavender", "Pearl White"],
    meaning="Совпадения — это расписание вселенной.",
    anim="5 с · кольца вращаются в разные стороны с разной скоростью, в момент выравнивания сердце вспыхивает.",
    desc="An armillary sphere of rose-gold rings around a crystal heart. The stars align — on schedule.",
    season="New Year — Midnight Astrolabe · Summer — Solstice Astrolabe",
    prompt="an armillary sphere of three polished rose-gold rings engraved with constellations on a slim stand, an iridescent crystal heart at the centre, tiny pearl planets on the rings")

nft(n=26, slug="26-dance-with-me", name="Dance With Me", ru="Потанцуй со мной", rarity="Uncommon", price=8,
    category="First Meeting", obj="Mirror Ball", material="Lavender Glass", metal="Silver Chrome", color="Lilac",
    emotion="Joy", connection="First Meeting", effect="Light Spots",
    concept="Вечеринка, где вы встретились.",
    design="Диско-шар из лавандовых зеркальных плиток на атласной ленте; одна плитка — розовое сердце.",
    silhouette="Сфера на ленте.",
    materials=["lavender mirror tiles", "silver chrome", "lilac satin ribbon"], colors=["Lilac", "Soft Lavender", "Pearl White"],
    meaning="Иногда всё начинается с танца.",
    anim="3 с · шар вращается, зайчики-сердечки скользят вокруг.",
    desc="A lavender mirror ball with one heart-shaped tile. The night you met.",
    season="New Year — Midnight Disco · Summer — Rooftop Disco",
    prompt="a disco mirror ball covered in small lavender mirror tiles, one tile shaped like a pink heart, hanging from a lilac satin ribbon, casting soft heart-shaped light spots")

nft(n=27, slug="27-time-flies", name="Time Flies With You", ru="С тобой время летит", rarity="Rare", price=20,
    category="Memories", obj="Hourglass", material="Optical Crystal", metal="Rose Gold", color="Dusty Pink",
    emotion="Presence", connection="Time Together", effect="Sand Flow",
    concept="С тобой время летит.",
    design="Песочные часы: две хрустальные колбы в rose-gold раме из четырёх колонн; розовый глиттер-песок складывается внизу в сердце.",
    silhouette="Классические песочные часы.",
    materials=["optical crystal bulbs", "rose gold frame", "pink glitter sand"], colors=["Dusty Pink", "Rose Gold", "Pearl White"],
    meaning="Время, проведённое вместе, течёт иначе.",
    anim="4 с · песок течёт, внизу растёт сердце; часы делают плавный переворот (бесшовно).",
    desc="An hourglass of pink glitter sand that settles into a heart. Time flies with you.",
    season="New Year — Countdown · Anniversary — Our Time",
    prompt="a luxury hourglass with two optical crystal bulbs inside a polished rose-gold frame of four slim columns, pink glitter sand falling and forming a heart in the lower bulb")

nft(n=28, slug="28-our-song", name="Our Song", ru="Наша песня", rarity="Epic", price=55,
    category="Music", obj="Music Box", material="Glossy Enamel", metal="Rose Gold", color="Soft Lavender",
    emotion="Romance", connection="Shared Taste", effect="Rotation",
    concept="Мелодия, которая стала вашей.",
    design="Шкатулка из лавандовой эмали с rose-gold фурнитурой; крышка открыта, внутри зеркало и вращающееся на шпинделе хрустальное сердце; сбоку — заводной ключик.",
    silhouette="Открытая шкатулка с поднятой крышкой.",
    materials=["glossy lavender enamel", "rose gold hardware", "mirror", "crystal heart"], colors=["Soft Lavender", "Rose Gold", "Pearl White"],
    meaning="У каждой пары есть своя песня.",
    anim="5 с · сердце медленно вращается, заводной ключ поворачивается, ноты-искры поднимаются.",
    desc="A lavender music box with a turning crystal heart. It only plays your song.",
    season="Winter — Nutcracker Night · Valentine — Ruby Box",
    prompt="an open music box in glossy lavender enamel with rose-gold hardware, a small mirror inside the lid, a crystal heart turning on a spindle, a tiny rose-gold winding key on the side")

nft(n=29, slug="29-secret-seal", name="Secret Seal", ru="Тайная печать", rarity="Uncommon", price=9,
    category="Secret Symbols", obj="Seal Stamp", material="Pink Crystal", metal="Rose Gold", color="Deep Plum",
    emotion="Loyalty", connection="Secret Code", effect="Imprint",
    concept="Ваш тайный знак, понятный только вам.",
    design="Печать для сургуча: ручка из розового хрусталя, основание rose gold с гравировкой двух переплетённых сердец; рядом — капля сливового воска.",
    silhouette="Вертикальная печать-«грибок».",
    materials=["pink crystal handle", "engraved rose gold", "plum wax"], colors=["Deep Plum", "Rose Gold", "Dusty Pink"],
    meaning="У настоящих связей есть свой язык.",
    anim="3 с · печать опускается, оставляет оттиск сердец, поднимается; оттиск мягко светится.",
    desc="A crystal seal that prints two intertwined hearts. Your private language.",
    season="Valentine — Ruby Wax · Winter — Silver Wax",
    prompt="a wax seal stamp with a faceted pink crystal handle and a polished rose-gold base engraved with two intertwined hearts, a drop of deep plum sealing wax beside it")

nft(n=30, slug="30-thread-of-fate", name="Thread of Fate", ru="Нить судьбы", rarity="Legendary", price=180,
    category="Connection", obj="Twin Rings & Thread", material="Satin & Crystal", metal="Rose Gold", color="Lilac",
    emotion="Destiny", connection="Destiny", effect="Glowing Thread",
    concept="Легенда о невидимой нити, которая связывает двоих, предназначенных друг другу. Нить может растягиваться и путаться, но не рвётся.",
    design="Два тонких rose-gold кольца, связанные светящейся лиловой атласной нитью; нить образует знак бесконечности и в центре — узел-сердце из хрусталя.",
    silhouette="Два кольца + нить-бесконечность между ними.",
    materials=["polished rose gold", "lilac satin thread (glowing)", "crystal knot"], colors=["Lilac", "Rose Gold", "Pearl White", "Deep Plum"],
    meaning="Настоящие связи не случайны.",
    anim="5 с · нить течёт по контуру бесконечности световым импульсом, кольца медленно вращаются навстречу, узел-сердце бьётся.",
    desc="Two rose-gold rings tied by a glowing satin thread. It can stretch and tangle — but never breaks.",
    season="Valentine — Red Thread (1/1) · Anniversary — Golden Thread",
    prompt="two slim polished rose-gold rings tied together by a softly glowing lilac satin thread that forms an infinity loop, a small crystal heart knot at the centre of the thread")

assert len(NFTS) == 30
from collections import Counter
assert Counter(x["rarity"] for x in NFTS) == {"Common": 10, "Uncommon": 8, "Rare": 6, "Epic": 4, "Legendary": 2}
assert [x["n"] for x in NFTS] == list(range(1, 31))
